-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity p_anonymous_namespace_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_input_r_AWVALID : OUT STD_LOGIC;
    m_axi_input_r_AWREADY : IN STD_LOGIC;
    m_axi_input_r_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_input_r_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_r_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_input_r_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_input_r_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_input_r_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_input_r_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_r_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_input_r_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_r_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_r_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_r_WVALID : OUT STD_LOGIC;
    m_axi_input_r_WREADY : IN STD_LOGIC;
    m_axi_input_r_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_input_r_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_r_WLAST : OUT STD_LOGIC;
    m_axi_input_r_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_r_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_r_ARVALID : OUT STD_LOGIC;
    m_axi_input_r_ARREADY : IN STD_LOGIC;
    m_axi_input_r_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_input_r_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_r_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_input_r_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_input_r_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_input_r_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_input_r_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_r_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_input_r_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_r_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_input_r_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_r_RVALID : IN STD_LOGIC;
    m_axi_input_r_RREADY : OUT STD_LOGIC;
    m_axi_input_r_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_input_r_RLAST : IN STD_LOGIC;
    m_axi_input_r_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_r_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_r_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_input_r_BVALID : IN STD_LOGIC;
    m_axi_input_r_BREADY : OUT STD_LOGIC;
    m_axi_input_r_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_input_r_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_input_r_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    input_offset : IN STD_LOGIC_VECTOR (29 downto 0);
    blocks_base : IN STD_LOGIC_VECTOR (31 downto 0);
    num_blocks : IN STD_LOGIC_VECTOR (31 downto 0);
    bx : IN STD_LOGIC_VECTOR (29 downto 0);
    by : IN STD_LOGIC_VECTOR (29 downto 0);
    bz : IN STD_LOGIC_VECTOR (30 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of p_anonymous_namespace_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (12 downto 0) := "0000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (12 downto 0) := "0000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (12 downto 0) := "0000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (12 downto 0) := "0000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (12 downto 0) := "0000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (12 downto 0) := "0000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (12 downto 0) := "0001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (12 downto 0) := "0010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_lv32_C04 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000110000000100";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal input_r_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal input_r_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal bz_cast_fu_169_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bz_cast_reg_310 : STD_LOGIC_VECTOR (31 downto 0);
    signal by_cast_fu_173_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal by_cast_reg_315 : STD_LOGIC_VECTOR (31 downto 0);
    signal bx_cast_fu_177_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bx_cast_reg_320 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_cast_fu_181_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sext_cast_reg_325 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_fu_189_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_332 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_14_fu_194_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal i_14_reg_336 : STD_LOGIC_VECTOR (30 downto 0);
    signal next_mul_fu_200_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal next_mul_reg_341 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_offset_fu_206_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_offset_reg_346 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_addr_reg_353 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_addr_1_reg_359 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_ioackin_m_axi_input_r_ARREADY : STD_LOGIC;
    signal input_addr_2_reg_365 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_bx_reg_371 : STD_LOGIC_VECTOR (31 downto 0);
    signal block_by_reg_376 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_171_fu_278_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_171_reg_381 : STD_LOGIC_VECTOR (0 downto 0);
    signal block_bz_reg_386 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_172_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_172_reg_391 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_reg_136 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal or_cond1_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_mul_reg_147 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_p_0_phi_fu_162_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_0_reg_158 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_cast_fu_220_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum3_cast_fu_244_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sum6_cast_fu_268_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_reg_ioackin_m_axi_input_r_ARREADY : STD_LOGIC := '0';
    signal i_cast_fu_185_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_166_cast_fu_211_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sum_fu_215_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_167_fu_230_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_168_cast_fu_235_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sum3_fu_239_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_169_fu_254_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_170_cast_fu_259_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal sum6_fu_263_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal tmp_173_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (12 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_ioackin_m_axi_input_r_ARREADY_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_ioackin_m_axi_input_r_ARREADY <= ap_const_logic_0;
            else
                if ((((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_sig_ioackin_m_axi_input_r_ARREADY = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_sig_ioackin_m_axi_input_r_ARREADY = ap_const_logic_1)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_sig_ioackin_m_axi_input_r_ARREADY = ap_const_logic_1)))) then 
                    ap_reg_ioackin_m_axi_input_r_ARREADY <= ap_const_logic_0;
                elsif ((((m_axi_input_r_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((m_axi_input_r_ARREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_const_logic_1 = ap_CS_fsm_state3) and (m_axi_input_r_ARREADY = ap_const_logic_1)))) then 
                    ap_reg_ioackin_m_axi_input_r_ARREADY <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv32_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state13) and ((tmp_reg_332 = ap_const_lv1_0) or (or_cond1_fu_295_p2 = ap_const_lv1_1)))) then 
                    ap_return_preg <= ap_phi_mux_p_0_phi_fu_162_p4;
                end if; 
            end if;
        end if;
    end process;


    i_reg_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_cond1_fu_295_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13) and (tmp_reg_332 = ap_const_lv1_1))) then 
                i_reg_136 <= i_14_reg_336;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_reg_136 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;

    p_0_reg_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state13) and (or_cond1_fu_295_p2 = ap_const_lv1_1) and (tmp_reg_332 = ap_const_lv1_1))) then 
                p_0_reg_158 <= block_offset_reg_346;
            elsif (((tmp_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                p_0_reg_158 <= ap_const_lv32_FFFFFFFF;
            end if; 
        end if;
    end process;

    phi_mul_reg_147_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_cond1_fu_295_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state13) and (tmp_reg_332 = ap_const_lv1_1))) then 
                phi_mul_reg_147 <= next_mul_reg_341;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                phi_mul_reg_147 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((m_axi_input_r_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                block_bx_reg_371 <= m_axi_input_r_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((m_axi_input_r_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                block_by_reg_376 <= m_axi_input_r_RDATA;
                tmp_171_reg_381 <= tmp_171_fu_278_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((m_axi_input_r_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                block_bz_reg_386 <= m_axi_input_r_RDATA;
                tmp_172_reg_391 <= tmp_172_fu_282_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_fu_189_p2 = ap_const_lv1_1))) then
                block_offset_reg_346 <= block_offset_fu_206_p2;
                input_addr_reg_353 <= sum_cast_fu_220_p1(32 - 1 downto 0);
                next_mul_reg_341 <= next_mul_fu_200_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                bx_cast_reg_320 <= bx_cast_fu_177_p1;
                by_cast_reg_315 <= by_cast_fu_173_p1;
                bz_cast_reg_310 <= bz_cast_fu_169_p1;
                    sext_cast_reg_325(29 downto 0) <= sext_cast_fu_181_p1(29 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_14_reg_336 <= i_14_fu_194_p2;
                tmp_reg_332 <= tmp_fu_189_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_sig_ioackin_m_axi_input_r_ARREADY = ap_const_logic_1))) then
                input_addr_1_reg_359 <= sum3_cast_fu_244_p1(32 - 1 downto 0);
                input_addr_2_reg_365 <= sum6_cast_fu_268_p1(32 - 1 downto 0);
            end if;
        end if;
    end process;
    sext_cast_reg_325(32 downto 30) <= "000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, m_axi_input_r_RVALID, ap_CS_fsm_state3, ap_CS_fsm_state10, ap_CS_fsm_state4, ap_CS_fsm_state11, ap_CS_fsm_state5, ap_CS_fsm_state12, tmp_fu_189_p2, tmp_reg_332, ap_CS_fsm_state2, ap_sig_ioackin_m_axi_input_r_ARREADY, ap_CS_fsm_state13, or_cond1_fu_295_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((tmp_fu_189_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_sig_ioackin_m_axi_input_r_ARREADY = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_sig_ioackin_m_axi_input_r_ARREADY = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (ap_sig_ioackin_m_axi_input_r_ARREADY = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((m_axi_input_r_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                if (((m_axi_input_r_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((m_axi_input_r_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state13) and ((tmp_reg_332 = ap_const_lv1_0) or (or_cond1_fu_295_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, tmp_reg_332, ap_CS_fsm_state13, or_cond1_fu_295_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state13) and ((tmp_reg_332 = ap_const_lv1_0) or (or_cond1_fu_295_p2 = ap_const_lv1_1))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_p_0_phi_fu_162_p4_assign_proc : process(tmp_reg_332, block_offset_reg_346, ap_CS_fsm_state13, or_cond1_fu_295_p2, p_0_reg_158)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and (or_cond1_fu_295_p2 = ap_const_lv1_1) and (tmp_reg_332 = ap_const_lv1_1))) then 
            ap_phi_mux_p_0_phi_fu_162_p4 <= block_offset_reg_346;
        else 
            ap_phi_mux_p_0_phi_fu_162_p4 <= p_0_reg_158;
        end if; 
    end process;


    ap_ready_assign_proc : process(tmp_reg_332, ap_CS_fsm_state13, or_cond1_fu_295_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and ((tmp_reg_332 = ap_const_lv1_0) or (or_cond1_fu_295_p2 = ap_const_lv1_1)))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(tmp_reg_332, ap_CS_fsm_state13, or_cond1_fu_295_p2, ap_phi_mux_p_0_phi_fu_162_p4, ap_return_preg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) and ((tmp_reg_332 = ap_const_lv1_0) or (or_cond1_fu_295_p2 = ap_const_lv1_1)))) then 
            ap_return <= ap_phi_mux_p_0_phi_fu_162_p4;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;


    ap_sig_ioackin_m_axi_input_r_ARREADY_assign_proc : process(m_axi_input_r_ARREADY, ap_reg_ioackin_m_axi_input_r_ARREADY)
    begin
        if ((ap_reg_ioackin_m_axi_input_r_ARREADY = ap_const_logic_0)) then 
            ap_sig_ioackin_m_axi_input_r_ARREADY <= m_axi_input_r_ARREADY;
        else 
            ap_sig_ioackin_m_axi_input_r_ARREADY <= ap_const_logic_1;
        end if; 
    end process;

    block_offset_fu_206_p2 <= std_logic_vector(unsigned(blocks_base) + unsigned(phi_mul_reg_147));
        bx_cast_fu_177_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(bx),32));

        by_cast_fu_173_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(by),32));

        bz_cast_fu_169_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(bz),32));

    i_14_fu_194_p2 <= std_logic_vector(unsigned(i_reg_136) + unsigned(ap_const_lv31_1));
    i_cast_fu_185_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_reg_136),32));

    input_r_blk_n_AR_assign_proc : process(m_axi_input_r_ARREADY, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            input_r_blk_n_AR <= m_axi_input_r_ARREADY;
        else 
            input_r_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    input_r_blk_n_R_assign_proc : process(m_axi_input_r_RVALID, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state12) or (ap_const_logic_1 = ap_CS_fsm_state11) or (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            input_r_blk_n_R <= m_axi_input_r_RVALID;
        else 
            input_r_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    m_axi_input_r_ARADDR_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, input_addr_reg_353, input_addr_1_reg_359, input_addr_2_reg_365, ap_reg_ioackin_m_axi_input_r_ARREADY)
    begin
        if ((ap_reg_ioackin_m_axi_input_r_ARREADY = ap_const_logic_0)) then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                m_axi_input_r_ARADDR <= input_addr_2_reg_365;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                m_axi_input_r_ARADDR <= input_addr_1_reg_359;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                m_axi_input_r_ARADDR <= input_addr_reg_353;
            else 
                m_axi_input_r_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            m_axi_input_r_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    m_axi_input_r_ARBURST <= ap_const_lv2_0;
    m_axi_input_r_ARCACHE <= ap_const_lv4_0;
    m_axi_input_r_ARID <= ap_const_lv1_0;
    m_axi_input_r_ARLEN <= ap_const_lv32_1;
    m_axi_input_r_ARLOCK <= ap_const_lv2_0;
    m_axi_input_r_ARPROT <= ap_const_lv3_0;
    m_axi_input_r_ARQOS <= ap_const_lv4_0;
    m_axi_input_r_ARREGION <= ap_const_lv4_0;
    m_axi_input_r_ARSIZE <= ap_const_lv3_0;
    m_axi_input_r_ARUSER <= ap_const_lv1_0;

    m_axi_input_r_ARVALID_assign_proc : process(ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_reg_ioackin_m_axi_input_r_ARREADY)
    begin
        if ((((ap_reg_ioackin_m_axi_input_r_ARREADY = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((ap_reg_ioackin_m_axi_input_r_ARREADY = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((ap_reg_ioackin_m_axi_input_r_ARREADY = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            m_axi_input_r_ARVALID <= ap_const_logic_1;
        else 
            m_axi_input_r_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_input_r_AWADDR <= ap_const_lv32_0;
    m_axi_input_r_AWBURST <= ap_const_lv2_0;
    m_axi_input_r_AWCACHE <= ap_const_lv4_0;
    m_axi_input_r_AWID <= ap_const_lv1_0;
    m_axi_input_r_AWLEN <= ap_const_lv32_0;
    m_axi_input_r_AWLOCK <= ap_const_lv2_0;
    m_axi_input_r_AWPROT <= ap_const_lv3_0;
    m_axi_input_r_AWQOS <= ap_const_lv4_0;
    m_axi_input_r_AWREGION <= ap_const_lv4_0;
    m_axi_input_r_AWSIZE <= ap_const_lv3_0;
    m_axi_input_r_AWUSER <= ap_const_lv1_0;
    m_axi_input_r_AWVALID <= ap_const_logic_0;
    m_axi_input_r_BREADY <= ap_const_logic_0;

    m_axi_input_r_RREADY_assign_proc : process(m_axi_input_r_RVALID, ap_CS_fsm_state10, ap_CS_fsm_state11, ap_CS_fsm_state12)
    begin
        if ((((m_axi_input_r_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12)) or ((m_axi_input_r_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((m_axi_input_r_RVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            m_axi_input_r_RREADY <= ap_const_logic_1;
        else 
            m_axi_input_r_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_input_r_WDATA <= ap_const_lv32_0;
    m_axi_input_r_WID <= ap_const_lv1_0;
    m_axi_input_r_WLAST <= ap_const_logic_0;
    m_axi_input_r_WSTRB <= ap_const_lv4_0;
    m_axi_input_r_WUSER <= ap_const_lv1_0;
    m_axi_input_r_WVALID <= ap_const_logic_0;
    next_mul_fu_200_p2 <= std_logic_vector(unsigned(phi_mul_reg_147) + unsigned(ap_const_lv32_C04));
    or_cond1_fu_295_p2 <= (tmp_171_reg_381 and tmp1_fu_290_p2);
    sext_cast_fu_181_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(input_offset),33));
        sum3_cast_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sum3_fu_239_p2),64));

    sum3_fu_239_p2 <= std_logic_vector(unsigned(sext_cast_reg_325) + unsigned(tmp_168_cast_fu_235_p1));
        sum6_cast_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sum6_fu_263_p2),64));

    sum6_fu_263_p2 <= std_logic_vector(unsigned(sext_cast_reg_325) + unsigned(tmp_170_cast_fu_259_p1));
        sum_cast_fu_220_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sum_fu_215_p2),64));

    sum_fu_215_p2 <= std_logic_vector(unsigned(sext_cast_reg_325) + unsigned(tmp_166_cast_fu_211_p1));
    tmp1_fu_290_p2 <= (tmp_173_fu_286_p2 and tmp_172_reg_391);
        tmp_166_cast_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(block_offset_fu_206_p2),33));

    tmp_167_fu_230_p2 <= std_logic_vector(signed(block_offset_reg_346) + signed(ap_const_lv32_1));
        tmp_168_cast_fu_235_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_167_fu_230_p2),33));

    tmp_169_fu_254_p2 <= std_logic_vector(signed(block_offset_reg_346) + signed(ap_const_lv32_2));
        tmp_170_cast_fu_259_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_169_fu_254_p2),33));

    tmp_171_fu_278_p2 <= "1" when (block_bx_reg_371 = bx_cast_reg_320) else "0";
    tmp_172_fu_282_p2 <= "1" when (block_by_reg_376 = by_cast_reg_315) else "0";
    tmp_173_fu_286_p2 <= "1" when (block_bz_reg_386 = bz_cast_reg_310) else "0";
    tmp_fu_189_p2 <= "1" when (signed(i_cast_fu_185_p1) < signed(num_blocks)) else "0";
end behav;
